# Generated by Django 6.0.2 on 2026-09-22 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('icon', models.CharField(default='◆', max_length=8, verbose_name='Иконка (эмодзи или символ)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Формат мероприятия',
                'verbose_name_plural': 'Форматы мероприятий',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ',
                'verbose_name_plural': 'Вопросы и ответы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('line_color', models.CharField(default='#e4312b', help_text='Цвет «ветки метро» для зала, например #e4312b', max_length=7, verbose_name='Цвет линии (HEX)')),
                ('line_number', models.PositiveSmallIntegerField(default=1, verbose_name='Номер линии')),
                ('short_description', models.CharField(max_length=255, verbose_name='Короткое описание')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('capacity_banquet', models.PositiveIntegerField(verbose_name='Вместимость (банкет)')),
                ('capacity_buffet', models.PositiveIntegerField(verbose_name='Вместимость (фуршет)')),
                ('area', models.PositiveIntegerField(verbose_name='Площадь, м²')),
                ('price_from', models.PositiveIntegerField(verbose_name='Цена от, ₽/гость')),
                ('features', models.TextField(blank=True, help_text='Каждая особенность — с новой строки', verbose_name='Особенности')),
                ('image', models.CharField(default='img/hall-depo.svg', max_length=200, verbose_name='Картинка (путь в static)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MenuPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('price_per_person', models.PositiveIntegerField(verbose_name='Цена, ₽/гость')),
                ('items', models.TextField(help_text='Каждая позиция — с новой строки', verbose_name='Состав')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Хит')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Банкетное меню',
                'verbose_name_plural': 'Банкетные меню',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Имя')),
                ('event', models.CharField(blank=True, max_length=100, verbose_name='Мероприятие')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Оценка (1-5)')),
                ('created_at', models.DateField(verbose_name='Дата')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('date', models.DateField(verbose_name='Дата мероприятия')),
                ('guests', models.PositiveIntegerField(verbose_name='Количество гостей')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_work', 'В работе'), ('done', 'Подтверждена'), ('cancel', 'Отменена')], default='new', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('event_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venue.eventformat', verbose_name='Формат')),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venue.hall', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
