# Generated by Django 6.0.2 on 2026-09-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('topic', models.CharField(blank=True, max_length=150, verbose_name='Тема')),
                ('organizer', models.CharField(blank=True, max_length=150, verbose_name='Организатор')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('short_description', models.CharField(max_length=255, verbose_name='Короткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.CharField(blank=True, max_length=200, verbose_name='Картинка (путь в static)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Событие афиши',
                'verbose_name_plural': 'Афиша',
                'ordering': ['date', 'time'],
            },
        ),
    ]
