# Generated by Django 6.0.2 on 2026-09-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0003_hall_image_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='schedule',
            field=models.CharField(blank=True, help_text='Например «Каждое утро». Если заполнено, событие не пропадает из афиши после даты.', max_length=100, verbose_name='Регулярность'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='date',
            field=models.DateField(help_text='Для регулярного события — дата первого проведения', verbose_name='Дата'),
        ),
    ]
