# Generated by Django 6.1.1 on 2026-09-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0004_poster_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Если пусто — сгенерируется автоматически', max_length=160, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='hall',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Если пусто — сгенерируется автоматически', max_length=70, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='hall',
            name='slug',
            field=models.SlugField(blank=True, help_text="Человекопонятный URL, например 'depo'", max_length=120, null=True, unique=True, verbose_name='URL'),
        ),
    ]
