# Generated by Django 6.1.1 on 2026-09-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0005_hall_meta_description_hall_meta_title_hall_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='slug',
            field=models.SlugField(blank=True, help_text="Человекопонятный URL, например 'kviz-60-sekund'", max_length=160, null=True, unique=True, verbose_name='URL'),
        ),
    ]
